version: '3'

tasks:
  test:
    desc: "Run all Go tests"
    cmds:
      - go test ./...
  build:
    desc: "Build the project"
    cmds:
      - git add go.mod  # This is important otherwise build will throw error
      - go run main.go build
  lint:
    desc: "Run golangci-lint"
    cmds:
      - golangci-lint run ./...