version: '3'

tasks:
  test:
    desc: "Run all Go tests"
    cmds:
      - go test ./...
  build:
    desc: "Build the project"
    cmds:
      - go run main.go build
  lint:
    desc: "Run golangci-lint"
    cmds:
      - golangci-lint run ./...