package cmd

import (
	"fmt"
	"os"

	"github.com/buildsafe/bsf/cmd/init"
	"github.com/buildsafe/bsf/styles"
	"github.com/spf13/cobra"
)

func init() {
	if os.Getenv("BSF_DEBUG_MODE") == "true" {
		rootCmd.AddCommand(cleanCmd)

	}

}

var cleanCmd = &cobra.Command{
	Use:   "clean",
	Short: "cleans the autogenerated bsf files and directories",
	Run: func(cmd *cobra.Command, args []string) {
		if err := cleanUp(); err != nil {
			fmt.Println(styles.ErrorStyle.Render("Error during cleanup:", err.Error()))
			os.Exit(1)
		}
		fmt.Println(styles.SuccessStyle.Render("Autogenerated bsf files/dirs cleaned successfully"))
	},
}

// cleanUp deletes the autogenerated BSF files and directories.
func cleanUp() {
	configs := []string{"bsf", "bsf.hcl", "bsf.lock"}

	for _, f := range configs {
		os.RemoveAll(f)
	}
}
