package cmd

import (
	"fmt"
	"github.com/buildsafe/bsf/cmd/init"
	"os"
)

func init() {
	rootCmd.AddCommand(cleanCmd)
}

var cleanCmd = &cobra.Command{
	Use:   "clean",
	Short: "Clean autogenerated BSF files and directories",
	Run: func(cmd *cobra.Command, args []string) {
		if os.Getenv("BSF_DEBUG_MODE") == "" {
			fmt.Println("BSF_DEBUG_MODE is not enabled. Skipping clean.")
			return
		}

		err := cleanUp() // Call the cleanUp function
		if err != nil {
			fmt.Printf("Error during cleanup: %v\n", err)
		} else {
			fmt.Println("Autogenerated BSF files and directories cleaned successfully.")
		}
	},
}

// cleanUp deletes the autogenerated BSF files and directories.
func cleanUp() error {
	configs := []string{"bsf", "bsf-result", "bsf.hcl", "bsf.lock"}

	for _, f := range configs {
		if err := os.RemoveAll(f); err != nil {
			return fmt.Errorf("failed to remove %s: %v", f, err)
		}
	}

	return nil
}
