package clean

import (
	"fmt"

	in "github.com/buildsafedev/bsf/cmd/init"
	"github.com/buildsafedev/bsf/cmd/styles"
	"github.com/spf13/cobra"
)

var CleanCmd = &cobra.Command{
	Use:   "clean",
	Short: "cleans the autogenerated bsf files and directories",
	Long: `cleans the autogenerated bsf files and directories.
	Cleans bsf.hcl, bsf.lock, /bsf
	`,
	Run: func(cmd *cobra.Command, args []string) {
		clean()
	},
}

func clean() {
	fmt.Println(styles.SucessStyle.Render("Cleaning autogenerated bsf files and directories"))
	in.CleanUp()
}
