name: BuildSafe CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Setup Nix development environment
        uses: nicknovitski/nix-develop@v1
        with:
          arguments: bsf/.#devShell

      - name: Run tests
        run: task test

      - name: Build app
        run: task build

      - name: Run GolangCI-Lint
        run: task lint
        continue-on-error: true
